// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6TZL-6YRz1pCvSYqTOVHY6XLFKA-q5J0',
    appId: '1:417207197323:web:c8ebb5c125b68a3428be8e',
    messagingSenderId: '417207197323',
    projectId: 'miniproject-4f2b9',
    authDomain: 'miniproject-4f2b9.firebaseapp.com',
    storageBucket: 'miniproject-4f2b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk8tkLUGPE6EfI6XGy4Mi6rmlO_4mZeBk',
    appId: '1:417207197323:android:7b6bfb14328657ff28be8e',
    messagingSenderId: '417207197323',
    projectId: 'miniproject-4f2b9',
    storageBucket: 'miniproject-4f2b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs-hGD8Oo2TD1IDgLJSHqkau9wLFlMfRA',
    appId: '1:417207197323:ios:e763187d6222375b28be8e',
    messagingSenderId: '417207197323',
    projectId: 'miniproject-4f2b9',
    storageBucket: 'miniproject-4f2b9.firebasestorage.app',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs-hGD8Oo2TD1IDgLJSHqkau9wLFlMfRA',
    appId: '1:417207197323:ios:e763187d6222375b28be8e',
    messagingSenderId: '417207197323',
    projectId: 'miniproject-4f2b9',
    storageBucket: 'miniproject-4f2b9.firebasestorage.app',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6TZL-6YRz1pCvSYqTOVHY6XLFKA-q5J0',
    appId: '1:417207197323:web:0e1410146358eabe28be8e',
    messagingSenderId: '417207197323',
    projectId: 'miniproject-4f2b9',
    authDomain: 'miniproject-4f2b9.firebaseapp.com',
    storageBucket: 'miniproject-4f2b9.firebasestorage.app',
  );
}
